### ISSUE TITLE
java.nio.file.AccessDeniedException in Setup step 2 

### ISSUE THREAD

**Issue by mblo** [mblo/hire-cluster-simulator#1]
_(some users report the following issue)_

Setup step 2, i.e., `docker run -it -v $PWD:/app --rm asplos21-hire/runner sbt assembly`, gives the following error log

```
java.nio.file.AccessDeniedException: /app/project
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:689)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:796)
        at java.base/java.nio.file.Files.createDirectories(Files.java:782)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:290)
        at sbt.xMain$.getSocketOrExit(Main.scala:120)
        at sbt.xMain$.run(Main.scala:75)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:120)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.nio.file.AccessDeniedException: /app/project
```

Host system
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Comment by mblo** [comment]
This seems to be an issue with the mounted local directory. When running the container, we mount the local directory in the container. Looks like there was an issue with setting the permissions and user correctly. 

Please check again with the updated version.
(Also note the updated build command)

Tested on:
- Mac Os Big Sur, Darwin 20.2.0, Docker version 20.10.0, build 7287ab3
- Ubuntu 19.10, Linux 5.3.0-64-generic, Docker version 19.03.6, build 369ce74a3c

**Comment by mblo** [comment]
This problem seems to be resolved.
